### ISSUE TITLE
Question : can't this addon somehow waste server performance ?

### ISSUE THREAD

**Issue by fladna9** [DreamNetwork/gmod-tauntmenu#1]
Hi ! Might not be an issue, but I have a question.
In _gmod-tauntmenu/lua/autorun/server/prophunt_tauntmenu.lua_, line _152_ we can find :
`hook.Add("Think", "TauntList_DetectUpdate", function()`

My question is because it is run every tick on the server, couldn't this waste a lot of computation ?
As Garry's Wiki says here : https://wiki.garrysmod.com/page/GM/Think

> GM:Think()
> 
> Description
> Called every frame on client and every tick on server.

May this be more efficient : https://wiki.garrysmod.com/page/GM/Initialize ?

> GM:Initialize()
> 
> Description
> Called after the gamemode loads and starts.

Sorry, i'm learning lua and my question might seems a bit odd, but, just wanna know...

**Comment by icedream** [comment]
Hello!

Yes, "Think" does get triggered on every tick. I think the original idea I had behind this was that maybe at the time where the "Initialize" hook that gets registered by the taunt menu gets called not all tauntpacks have registered properly yet. In fact, it is possible for a tauntpack to register itself at other occasions outside of or even specifically after the "Initialize" event. This would lead to taunts not being displayed in the menu at all.

Now of course, hooking the "Think" event is a bit aggressive and I realize that, however it doesn't seem to cause severe performance losses and most importantly: It does what it is supposed to do 100% of the time. Of course I'm open for people to prove me wrong regarding this but it has been a while since I last touched the code here.

Hope this helps you understanding the decision!

**Comment by fladna9** [comment]
Sorry for the delay of my answer. Thanks for this explanation, it helps me understand the choices you've made, as i'm myself writing an addon (Auntotaunt for PropHunt).
